name: Deploy Verselib Frontend

on:
  push:
    branches:
      - main       # Run this job whenever code is pushed to main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "🚀 Starting Verselib Frontend deployment..."
            cd /var/www
            ./deploy_verselib.sh
            echo "✅ Deployment completed!"
